version: '26.0.0'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/JWTtestingDatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mbhaskersaaiteja_1996
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: JWTtestingDatabase
      MYSQL_ROOT_PASSWORD: Mbhaskersaaiteja_1996
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
